version: "3.9"

services:
  telegram_gpt_bot:
    image: telegram_gpt_bot_image
    hostname: telegram_gpt_bot
    container_name: telegram_gpt_bot_container
    command: python3 main.py
    build:
      context: TelegramGPT/
      dockerfile: ./Dockerfile
    restart: "always"
    environment:
      - TZ=Europe/Moscow
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - BOT_TOKEN=${BOT_TOKEN}
      - ADMIN_CHAT_ID=${ADMIN_CHAT_ID}
      - LOG_LEVEL=${LOG_LEVEL}
      - IS_PROD=prod
    logging:
      driver: "local"
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
