version: "3.9"

services:
  telegram_gpt_bot:
    image: telegram_gpt_bot_image
    hostname: telegram_gpt_bot
    container_name: telegram_gpt_bot_container
    command: python3 main.py
    build:
      context: TelegramGPT/
      dockerfile: ./Dockerfile
    restart: "always"
    environment:
      - TZ=Europe/Moscow
      - IS_PROD=prod
    logging:
      driver: "local"
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
